FROM alpine:3.15.0
LABEL "image"="orcamento-app"
RUN apk add --no-cache curl tar bash openjdk11
ARG MAVEN_VERSION=3.6.3
ARG USER_HOME_DIR="/root"
RUN mkdir -p /usr/share/maven && \
    curl -fsSL http://apache.osuosl.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz | tar -xzC /usr/share/maven --strip-components=1 && \
    ln -s /usr/share/maven/bin/mvn /usr/bin/mvn
ENV MAVEN_HOME /usr/share/maven
ENV MAVEN_CONFIG "$USER_HOME_DIR/.m2"
ENV MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
ENTRYPOINT ["/usr/bin/mvn"]

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY pom.xml /usr/src/app
RUN mvn -T 1C install && rm -rf target
COPY src /usr/src/app
RUN mvn -v
RUN mvn package -T 1C -o -Dmaven.test.skip=true
EXPOSE 8080
ADD ./target/controle-orcamento-0.0.1-SNAPSHOT.jar /usr/src/app/app.jar
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom","-Dspring.profiles.active=container","-jar","/usr/src/app/app.jar"]



